version: 2

sources:
  - name: salesforce
    database: windsor-dbt-development
    schema: Salesforce
    description: "Salesforce data tables for campaign funnel analysis"
    
    tables:
      - name: salesforce_campaigns
        description: "Salesforce campaigns data"
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: salesforce_leads 
        description: "Salesforce leads data"
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}